### ISSUE TITLE
파일명에 ',' 가 포함된 경우 다운로드 오류 

### ISSUE THREAD

**Issue by mintplo** [xpressengine/plugin-board#110]
<img width="542" alt="2017-04-12 2 26 49" src="https://cloud.githubusercontent.com/assets/5382029/24942478/35cdd452-1f8c-11e7-96d8-86176acc37cf.png">

파일명에 위와 같이 ',' 가 포함되는 경우 다운로드가 안됩니다.

첨부할 경우 해당 글자가 포함된 경우 오류로 띄우고 첨부를 못하게 하거나

다운로드가 정상적으로 되도록 수정해야할것 같습니다.

**Comment by akasima** [comment]
https://answers.nuxeo.com/general/q/d8348e07fe5e441183bae07dfda00e40/Comma-in-file-name-cause-problem-in-Chrome-Browser

이런 문제인가 보네요. 
영어가 짧아서 읽지는 못하지만 크롬에서의 문제

**Comment by akasima** [comment]
코어에서 수정했습니다. 
https://github.com/xpressengine/xpressengine/commit/40affe769498077f908f6524c56197002a92e040
