### ISSUE TITLE
[건의] '목록' 버튼이 있었으면 합니다.

### ISSUE THREAD

**Issue by mireleader** [xpressengine/plugin-board#111]
현재.. 게시판에서
게시물 클릭해서 들어가면 '목록'으로 갈 수 있는 버튼이 없고..
게시글 하단에 목록들이 리스트로 나오는데요..

그와 별도로 '목록'으로 갈 수 있는 '목록' 버튼이 있었으면 합니다.

검토 부탁합니다.

**Comment by akasima** [comment]
네. 검토 하겠습니다.

**Comment by akasima** [comment]
디자인팀과 목록 버튼 추가에 대해서 논의했습니다.

기본 배포하는 스킨에서 버튼 영역을 좌/우로 나누어 볼때
좌측에는 기능 버튼이 달려있고 
우측에는 관리기능(수정,삭제) 버튼이 있습니다.

목록으로 이동하는 버튼을 추가하는게 어려운 일은 아니지만 좌/우측 영역에 버튼 속성들을 생각해 볼 때 어느 한곳에 버튼을 추가하기가 어렵습니다.

내부적으로 조금 더 논의해 보겠지만 현재는 추가 하지 않는것으로 결정했습니다.

목록 버튼은 하단에 리스트를 보여주지 않는 스킨을 제작할 경우 해당 스킨에서 버튼을 어디에 배치할 지 고민해 볼것 같습니다.

**Comment by akasima** [comment]
내부적인 검토 기간이 길어졌는데요. 
관련되서 추가로 결정된 사항이 없어서 이 이슈는 진행하기 어렵겠습니다.
목록으로 가기 버튼 추가에 대한 요구가 많이 있다면 다른 이슈를 만들어서 진행하면 좋겠습니다.

이슈 닫습니다.
