### ISSUE TITLE
get_board_title 함수 지원

### ISSUE THREAD

**Issue by akasima** [xpressengine/plugin-board#112]
https://www.xpressengine.io/qna/Board-%EB%AA%A8%EB%8D%B8%EC%97%90%EC%84%9C-Item-Title-%EC%A0%95%EB%B3%B4 요청에 따른 기능 추가

**Comment by akasima** [comment]
src/helpers.php 파일 추가하고 get_board_title() 함수 추가했습니다.

git으로 관리하시는 분은 `composer dump` 를 실행해서 autoload 가 갱신될 수 있도록 해야합니다.

**Comment by sangemi** [comment]
넵 고생이 많으십니다!!
근데 혹시
$documents = Board::limit($limit)->orderBy('createdAt', 'desc')->get();
foreach($documents as $do){
   $documents->boardTitle = get_board_title($model);
}
이런식으로 한 다음에 $documents를 view에 넘겨서 뿌려줘야 할듯한데
속도는 괜찮을까요..
foreach문 마다 쿼리를 날리게 되는것은 아닌지 모르겠습니다.

**Comment by akasima** [comment]
foreach 문 마다 쿼리 날립니다.

get_board_title($model); 자체가 타이틀을 바로 만드니까.. view 에서 직접 실행하면 되지 않을까요?

메인페이지에서 속도의 문제는 페이지 캐싱이나.. 속도 개선의 이슈로 넘기게 될것 같습니다.
