### ISSUE TITLE
게시글의 대댓글 삭제시 댓글수 카운팅 오류

### ISSUE THREAD

**Issue by khongchi** [xpressengine/plugin-board#120]
![image](https://user-images.githubusercontent.com/1772843/28408936-005dcd6e-6d74-11e7-9b19-20ad62ee732c.png)

심각한 오류는 아니지만  게시글에 대댓글 추가할 때에는 댓글수가 갱신 안 되는데, 대댓글을 삭제할 때는 댓글수가 갱신됩니다.

**Comment by jhyeon1010** [comment]
xpressengine/plugin-comment#29 에서 처리하겠습니다.
