### ISSUE TITLE
[beta.25] 게시판 확장 필드 기능 오류

### ISSUE THREAD

**Issue by smaker** [xpressengine/plugin-board#132]
확장 필드를 Category 타입으로 설정하고 등록 버튼을 클릭하면 아래와 같은 에러가 Toast에 나옵니다.

 `The given data was invalid.`

다른 타입은 이상없는데 카테고리 타입만 이러네요.

![screenshot-127 0 0 1-2017-10-23-20-26-13-426](https://user-images.githubusercontent.com/1732040/31886714-75a11700-b830-11e7-9ede-4b5d80b62b85.png)

**Comment by akasima** [comment]
https://github.com/xpressengine/xpressengine/issues/625 카테고리 추가할 때 오류는 여기서 수정하겠습니다.

**Comment by akasima** [comment]
코어에서 category id 를 처리하지 못하는 오류가 있었을 것으로 생각됩니다.
xpressengine/xpressengine#625 에서 카테고리 아이디 설정에 따른 오류를 없애기 위한 처리를 했으며 
이 문제는 코어 업데이트 하면 해결될 것으로 생각됩니다.
