### ISSUE TITLE
비밀글 사용 여부에 대한 옵션 필요

### ISSUE THREAD

**Issue by bnu** [xpressengine/plugin-board#136]
글 작성 시 항상 '비밀글'을 작성할 수 있습니다.

게시판 용도, 목적에 따라 '비밀글'을 작성할 수 없도록 제한해야 할 수 있습니다.
'비밀글' 사용 여부에 대한 설정 및 제한이 적용이 필요합니다.

**Comment by akasima** [comment]
비밀글 사용 / 사용안함 을 설정할 수 있도록 옵션 추가했습니다.


![2018-02-19 5 29 18](https://user-images.githubusercontent.com/5836237/36368417-7730d21e-159a-11e8-89cf-7a69b1c47c0a.png)
![2018-02-19 5 29 31](https://user-images.githubusercontent.com/5836237/36368421-79218014-159a-11e8-84d7-987a70893aa0.png)
