### ISSUE TITLE
게시판에 커버 이미지를 저장할 수 있도록 기능 수정

### ISSUE THREAD

**Issue by akasima** [xpressengine/plugin-board#179]
https://github.com/xpressengine/xpressengine/issues/745

**Comment by bnu** [comment]
b3b599e 커밋 이후 아래와 같은 오류 발생합니다.

게시물 수정 시 발생.

![2018-05-03 7 40 53](https://user-images.githubusercontent.com/53764/39572392-f321a1de-4f09-11e8-9f9b-33c9a7f37efd.png)
