### ISSUE TITLE
DB에 저장되는 grants 값 중 rating 값이 member 로 저장됩니다.

### ISSUE THREAD

**Issue by Laeng** [xpressengine/plugin-board#191]
XE3 에서 Rating 이 3가지를 사용하는데요! ( `guest`, `user`, `admin` ) 

```
"grants": "{"create":{"rating":"member","group":[],"user":[],"except":[]},"read":{"rating":"guest","group":[],"user":[],"except":[]},"list":{"rating":"guest","group":[],"user":[],"except":[]},"manage":{"rating":"manager","group":[],"user":[],"except":[]}}"
```

permissions 테이블에 저장되는 게시판 모듈의 garents 값 중 rating 값이 member 로 저장됩니다!
당연히 user 로 저장되는 줄 알았는데, member 로 저장이되어서 약간 헤매었습니다.

설정값을 member 대신 user 로 저장되었으면 좋겠습니다!

**Comment by Laeng** [comment]
좀더 알아보고 이슈 다시 올리겠습니다!

**Comment by bnu** [comment]
@jhyeon1010

**Comment by Laeng** [comment]
아하! 이미 고쳐진 문제였네요!!! 
BUN 님 말씀처럼 아직 DB 에 남은 것들인것 같습니다!
답변 고맙습니다!!
