### ISSUE TITLE
다이나믹 필드 카테고리

### ISSUE THREAD

**Issue by leeyoonwoo** [xpressengine/plugin-board#198]
다이나믹 필드로 카테고리를 생성 시 게시글 목록에서 안 나오는 이슈가 있습니다.

**Comment by woongbin** [comment]
용어의 혼돈이 있는것 같습니다.
<img width="1151" alt="2018-08-01 15 42 44" src="https://user-images.githubusercontent.com/15007903/43505857-2a98f75e-95a3-11e8-8dce-e5dfa517ff8f.png">
위에 표시된 분류에 카테고리를 생성하려면 아래 이미지에 체크된 게시판 설정 카테고리 관련 메뉴에서 카테고리를 추가하실 수 있습니다.
![2018-08-01 15 57 21](https://user-images.githubusercontent.com/15007903/43506064-e39d151e-95a3-11e8-845a-44cd858a07fb.png)

다이나믹 필드로 추가된 카테고리의 경우 아래와 같이 게시물 내용에 추가로 선택할 수 있는 카테고리로 출력됩니다.
![2018-08-01 16 01 30](https://user-images.githubusercontent.com/15007903/43506199-4fd643ae-95a4-11e8-9010-019445e176bf.png)

문의 주신 내용이 위 내용이 아닐 경우 다시 댓글 남겨주시면 확인해보도록 하겠습니다.
감사합니다.
