### ISSUE TITLE
갤러리형 등에서 썸네일 이미지의 비율 등이 깨지는 문제

### ISSUE THREAD

**Issue by bnu** [xpressengine/plugin-board#209]
background cover로 변경
notice 링크가 안 걸린 문제

**Comment by bnu** [comment]
완료

**Comment by inasis** [comment]
.board_list.gallery .thumb_area a 아래의
<img src="{{ $item->board_thumbnail_path }}" alt="">를 없앴습니다
이미지는 a태그의 background 로 들어갑니다
```
<div class="thumb_area">
  <a href="{{$urlHandler->getShow($item, Request::all())}}" style="background-image:url ('{{ $item->board_thumbnail_path }}')">
    @if($item->isNew($config->get('newTime')))
    @endif
  </a>
</div>
```
이 부분은 갤러리 게시판 이미지의 비율을 정하기 위한 CSS입니다
제가 지정한 코드는 정사각형입니다
```
.board_list.gallery .thumb_area a{
  position:relative;

  padding-top: 100%; /* 1:1 */
  /* padding-top: 75%; 4:3 */
  /* padding-top: 50%; 2:1 */

  background-position:center center;
  background-repeat: no-repeat;
  background-size: cover;
}
```
어떤 이미지를 올려도 항상 중앙으로 들어가며
크기에 엇나가는 부분은 잘려 나옵니다

**Comment by inasis** [comment]
a태그의 padding-top값을 지정하기 위해서는 width 값이 항상 지정되어 있어야 합니다

gallery의 경우는 .thumb_area 에서 width 값을 상속받았지만
blog의 경우는 230x140의 값으로 직접 지정해 주어야 했습니다
