### ISSUE TITLE
update 처리항목이 install 에 없음

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/plugin-board#219]
`Update::updateColumnsConfig` 함수에서 처리되는 항목이 install 시에는 적용되지 않고 update 호출시에 적용됨.
다른 항목들도 검토가 필요함

**Comment by kimyu711** [comment]
현재 별다른 적용없이 install시에 적용이 되는 것으로 확인되어 재현불가처리 하겠습니다.
