### ISSUE TITLE
유저의 추천이 있는 게시글을 copy 후 copy 된 게시글의 추천을 하면 추천수가 줄어드는 문제

### ISSUE THREAD

**Issue by Laeng** [xpressengine/plugin-board#227]
추천을 받은 게시글을 다른 게시판으로 copy 를 하게 되면, 다른 게시판으로 copy 된 게시글의 추천수까지 복사가 잘 됩니다.

이때 복사된 글에서 유저가 추천을 하게되면, 추천수가 0까 줄어드는 문제가 발생합니다.

추가로 복사된 게시글의 댓글도 원본 게시글 댓글과 연동되었으면 좋겠습니다

**Comment by akasima** [comment]
본문 copy 하는 방법만 생각했었는데..
다른 정보들과 연동하는 것에 대해서 생각해 보겠습니다.
copy 할 때 처리해야할게 상당히 많겠네요.

**Comment by Laeng** [comment]
댓글 연동의 경우 단순히 target id 만 변경해주면 끝날 줄 알았는데, 게시판별 부여된 instance id 까지 바꿔줘야 하는 것 같습니다.  플러그인으로 우회를 하고자 했으나 방법을 찾을 수 없네요 흑흑... ㅠㅠ

**Comment by woongbin** [comment]
- counter_log를 사용하는 추천, 비추천, 조회수에 같은 현상 발생
- 댓글의 경우 댓글 수만 복사되고 댓글은 복사 되지 않음
