### ISSUE TITLE
최근 게시물 위젯에 선택 게시판 변경

### ISSUE THREAD

**Issue by woongbin** [xpressengine/plugin-board#229]
최근 게시물 위젯에서 현재는 1개의 게시판의 글만 확인이 가능한데
복수의 게시판이나 전체 게시판의 게시물을 확인하는 옵션 추가

**Comment by kimyu711** [comment]
https://github.com/xpressengine/plugin-board/commit/6941153f8a28f67b390b23fc8b542024a6e396bd
