### ISSUE TITLE
XeroCommerce 테마와 게시판 스킨 동시에 사용 시에 개선되었으면 하는 사항

### ISSUE THREAD

**Issue by smaker** [xpressengine/plugin-board#232]
![screenshot-simplesoft io-2019 03 15-13-42-54](https://user-images.githubusercontent.com/1732040/54409164-b4420400-4728-11e9-820a-283ef338bda8.png)

XeroCommerce 테마와 게시판 스킨 동시에 사용 시, 상단 여백없이 메뉴 부분과 딱 달라붙는 이슈가 있습니다.

**Comment by akasima** [comment]
content container 스타일을 지정하면 될 것 같아요.
메인 페이지(leaflet) 외 페이지에서 스타일을 고정할 것 같습니다.

**Comment by smaker** [comment]
@akasima 그러면 어디를 수정해야 하나요?
