### ISSUE TITLE
게시판 설정 중 "출력 순서" 버그

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/plugin-board#242]
1.확장 필드를 추가
2. 추가한 "확장 필드"를 "출력 순서"에서 출력하도록 합니다.
3."확장 필드"를 삭제합니다.
4. 여전히 게시판 목록 페이지에서는 삭제한 확장 필드가 이전의 "출력 순서" 설정에 따라 출력되고 있습니다. 
이는 "출력 순서" 설정페이지에서 "저장"버튼을 눌러주면 해결됩니다.
확장 필드 편집이나 삭제시에 출력 순서 설정 업데이트하는 코드가 있는지, 잘 작동하는지 확인해야 할 것 같스빈다.

**Comment by xharpenParksuhyeon** [comment]
새롭게 추가된 확장 필드를 `출력 순서` 페이지에서 활성화 시키면 게시판 페이지에 노출됩니다.

![image](https://user-images.githubusercontent.com/54769955/126029257-cf09264f-7633-47d3-901c-65b23864a643.png)
![image](https://user-images.githubusercontent.com/54769955/126029302-0f48a8a1-9b98-4e0d-8c2e-7d0f2a0e6884.png)

그 후 추가된 확장 필드를 사용하지 않는 경우엔 삭제해 줍니다. 
이 후 게시판 페이지로 이동해도 삭제된 확장 필드가 계속 노출되는 걸 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/54769955/126029367-06f11502-6a29-47fd-8b95-e5b6eb7608e3.png)
![image](https://user-images.githubusercontent.com/54769955/126029374-4e9507b8-66c6-4f70-96b5-be5a309974a3.png)

이 문제를 해결하기 위해서는 `출력 순서` 페이지에서 저장 버튼을 눌러주면 해결됩니다.

![image](https://user-images.githubusercontent.com/54769955/126029442-5b697836-6e68-4e09-b194-330c53adf8f4.png)
![image](https://user-images.githubusercontent.com/54769955/126029459-22187dac-5a13-4c24-83a8-d8c4d178106e.png)

**Comment by xharpenParksuhyeon** [comment]
수정

![image](https://user-images.githubusercontent.com/54769955/126029601-0f7fa3de-9305-4cac-9fdc-c8eb6a2244c6.png)
![image](https://user-images.githubusercontent.com/54769955/126029617-be791800-4034-4c35-b985-2d6353753ade.png)
![image](https://user-images.githubusercontent.com/54769955/126029632-8777443d-e194-46f3-8a39-2ec39fdeeecf.png)
