### ISSUE TITLE
게시판 출력 순서 미적용 버그

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/plugin-board#243]
게시판 갤러리 스킨, 게시판 블로그 스킨에서는 "확장 필드"를 "출력 순서"에서 출력하도록 하여도 실제 출력이 안되는 문제가 있습니다.

**Comment by akasima** [comment]
게시판, 블로그 스킨등에서 표현하는데 한계가 있습니다. 
일반 목록형에서는 표시하도록 처리했느데, 이외 스킨에서는 표현에 한계가 있었습니다. 
XE1에서 사용하던 다른 스킨들도 확인해 보니 지원하지 않는 경우가 많았습니다. 

해당 기능은 표현 가능한 범위를 다시 체크하고 반영하겠습니다.

**Comment by woongbin** [comment]
- 순서 변경 기능은 기본형 스킨에서만 지원
- 1.0.10 버전에서 추가된 XE 갤러리 스킨, XE 웹진 스킨에서는 확장 필드를 출력하도록 지원하고 있습니다.
