### ISSUE TITLE
게시글 이동시 댓글 사라짐

### ISSUE THREAD

**Issue by Laeng** [xpressengine/plugin-board#252]
게시글 이동시 댓글이 사라집니다! 확인 부탁드립니다.

**Comment by akasima** [comment]
https://tech.joabee.com/freeboard/%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EC%9D%B4%EB%8F%99-%ED%85%8C%EC%8A%A4%ED%8A%B8

댓글이 살아있는데요. 혹시 복사 한걸까요?

**Comment by Laeng** [comment]
헉!... 그렇다면 제 쪽에서 문제가 발생한것 같아요!
자세하게 확인 후 다시 연락 드리겠습니다.
