### ISSUE TITLE
글작성 시 이미지 사이즈 편집 후 상세보기에서는 spill로 출력되는 이슈 

### ISSUE THREAD

**Issue by choijeong** [xpressengine/plugin-board#286]

**Comment by akasima** [comment]
에디터로 작성된 경우 compile 할 때 AbstractEditor 에 작성된 코드가 실행됩니다. ( ckeditor 는 AbstractEditor 을 extends 했습니다.)
https://github.com/xpressengine/xpressengine/blob/f60cffe762acce881b116b3959c318a90ce68bc4/core/src/Xpressengine/Editor/AbstractEditor.php#L587

`AbstractEditor::compile()` 에서 `AbstractEditor::image()` 가 실행되면서 image 관련 처리를 실행합니다.
https://github.com/xpressengine/xpressengine/blob/f60cffe762acce881b116b3959c318a90ce68bc4/core/src/Xpressengine/Editor/AbstractEditor.php#L759

여기에서 원본데이터 링크를 썸네일로 변경하게 되는데 width, height 가 처리 대상 attribute 에 포함되지 않아 크기 설정이 적용되지 않고 있습니다.

`AbstractEditor::image()` 에서 아래 코드로 수정하면 크기 값이 적용 됩니다.
수정 위치 
- https://github.com/xpressengine/xpressengine/blob/f60cffe762acce881b116b3959c318a90ce68bc4/core/src/Xpressengine/Editor/AbstractEditor.php#L761
- https://github.com/xpressengine/xpressengine/blob/f60cffe762acce881b116b3959c318a90ce68bc4/core/src/Xpressengine/Editor/AbstractEditor.php#L787
- 

```php
// $list = $this->getData($content, 'img.' . $this->getImageClassName(), ['data-id', 'data-media-id', 'style', 'alt', 'title']);
$list = $this->getData($content, 'img.' . $this->getImageClassName(), ['data-id', 'data-media-id', 'style', 'alt', 'title', 'width', 'height']);

...

/*
 sprintf(
                    '<img src="%s" class="%s" data-id="%s" data-media-id="%s" style="%s" alt="%s" title="%s" />',
                    $image->url(),
                    $this->getImageClassName(),
                    $data['data-id'],
                    $data['data-media-id'],
                    $data['style'],
                    $data['alt'],
                    $data['title']
                )
*/

sprintf(
                    '<img src="%s" class="%s" data-id="%s" data-media-id="%s" style="%s" alt="%s" title="%s" width="%s" height="%s"/>',
                    $image->url(),
                    $this->getImageClassName(),
                    $data['data-id'],
                    $data['data-media-id'],
                    $data['style'],
                    $data['alt'],
                    $data['title'],
                    $data['width'],
                    $data['height']
                )


```
