### ISSUE TITLE
게시판 단위가 아닌 게시물 단위의 익명설정 기능

### ISSUE THREAD

**Issue by bi-kim** [xpressengine/plugin-board#296]

**Comment by xharpenParksuhyeon** [comment]
작성자가 임의로 익명 설정할 수 있게 하는 `임의 사용` 기능을 추가합니다.



<img width="681" alt="스크린샷 2021-08-03 오전 12 27 57" src="https://user-images.githubusercontent.com/54769955/127886016-3b8b650c-3a25-48c0-98d3-b4428b3eb3ef.png">

<img width="707" alt="스크린샷 2021-08-03 오전 12 28 08" src="https://user-images.githubusercontent.com/54769955/127886058-3bb2d30f-5117-481f-be73-0ea336bef986.png">

----

<img width="998" alt="스크린샷 2021-08-03 오전 12 29 18" src="https://user-images.githubusercontent.com/54769955/127886214-3bffd518-c229-4ccf-ab5d-08d182c7ac38.png">

---

## 익명 작성
<img width="950" alt="스크린샷 2021-08-03 오전 12 31 16" src="https://user-images.githubusercontent.com/54769955/127886460-9058888f-4df6-43de-9b18-0c5956e1a7b0.png">

## 익명 사용 안하고 작성
<img width="929" alt="스크린샷 2021-08-03 오전 12 32 37" src="https://user-images.githubusercontent.com/54769955/127886641-d1bdcff6-0364-4312-8943-b7fd5adab277.png">
