### ISSUE TITLE
특정 환경에서 미리보기 미지원 문제

### ISSUE THREAD

**Issue by mAKEkr** [xpressengine/plugin-board#37]
https://overwal.kr/free
미리보기 누른 뒤에 .read_body쪽을 보면 .xe_content부분, 즉 내용부분이 비어있습니다.
공홈도 그런줄알았는데 공홈은 아니네요.

웹서버 환경
- Nginx 1.11.2
- PHP 7.0.8
- PHP-FPM로 통신
- https로 연결 이용중

게시물 작성시 게시물안에서 내용은 잘보이는 상황입니다.
XE3은 git으로 설치했고 모든 플러그인 업데이트는 완료한 상태입니다.
laravel.log 혹은 php상에 error.log로 찍히는건 없는 상황입니다.

**Comment by akasima** [comment]
공홈을 업데이트 못해서 공홈엔 문제가 없는거네요 ;;

문제점 확인했습니다. 문서 출력 부분을 수정하면서 미리보기를 빠트렸네요.
감사합니다!
