### ISSUE TITLE
글 링크 주소에서 'page' parameter 제거

### ISSUE THREAD

**Issue by bnu** [xpressengine/plugin-board#40]
목록 등에서 게시물의 주소에 포함된 'page' parameter를 제거해야 합니다.

게시물로 직접 접근 시 게시물 내용의 하단에 게시물 목록을 보여줘야 한다면, 'page' parameter 없이도 해당 게시물이 위치한 페이지를 가리켜 목록을 표시해야 합니다.

**Comment by akasima** [comment]
#41 에서 처리되었습니다.
